version: '3'

services:
  web:
    build: .
    ports:
      - "8001:8000" # Port externe:interne
    command: >
      bash -c "python manage.py migrate &&
              python manage.py collectstatic --no-input &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code # Montage du code source
      - static_volume:/code/staticfiles
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persistance des données
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Volume pour la DB
  static_volume: # Volume pour les fichiers statiques
